//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globe.Xml.Serialization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globe.Xml.Serialization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyQualifiedName.
        /// </summary>
        internal static string AssemblyQualifiedName {
            get {
                return ResourceManager.GetString("AssemblyQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant.
        /// </summary>
        internal static string Constant {
            get {
                return ResourceManager.GetString("Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldInfo.
        /// </summary>
        internal static string FieldInfo {
            get {
                return ResourceManager.GetString("FieldInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Constant.
        /// </summary>
        internal static string NoConstant {
            get {
                return ResourceManager.GetString("NoConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Readeable.
        /// </summary>
        internal static string NoReadeable {
            get {
                return ResourceManager.GetString("NoReadeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SerializableData.
        /// </summary>
        internal static string NoSerializableData {
            get {
                return ResourceManager.GetString("NoSerializableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Writeable.
        /// </summary>
        internal static string NoWriteable {
            get {
                return ResourceManager.GetString("NoWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyInfo.
        /// </summary>
        internal static string PropertyInfo {
            get {
                return ResourceManager.GetString("PropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readeable.
        /// </summary>
        internal static string Readeable {
            get {
                return ResourceManager.GetString("Readeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerializableData.
        /// </summary>
        internal static string SerializableData {
            get {
                return ResourceManager.GetString("SerializableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerializableData collection count.
        /// </summary>
        internal static string SerializableDataCollectionCount {
            get {
                return ResourceManager.GetString("SerializableDataCollectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagName.
        /// </summary>
        internal static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writeable.
        /// </summary>
        internal static string Writeable {
            get {
                return ResourceManager.GetString("Writeable", resourceCulture);
            }
        }
    }
}
