//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jx.Drawing.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jx.Drawing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly 的本地化字符串。
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AssemblyQualifiedName 的本地化字符串。
        /// </summary>
        internal static string AssemblyQualifiedName {
            get {
                return ResourceManager.GetString("AssemblyQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant 的本地化字符串。
        /// </summary>
        internal static string Constant {
            get {
                return ResourceManager.GetString("Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FieldInfo 的本地化字符串。
        /// </summary>
        internal static string FieldInfo {
            get {
                return ResourceManager.GetString("FieldInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FieldName 的本地化字符串。
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GridManager 的本地化字符串。
        /// </summary>
        internal static string GridManager {
            get {
                return ResourceManager.GetString("GridManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Constant 的本地化字符串。
        /// </summary>
        internal static string NoConstant {
            get {
                return ResourceManager.GetString("NoConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Data 的本地化字符串。
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Readeable 的本地化字符串。
        /// </summary>
        internal static string NoReadeable {
            get {
                return ResourceManager.GetString("NoReadeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No SerializableData 的本地化字符串。
        /// </summary>
        internal static string NoSerializableData {
            get {
                return ResourceManager.GetString("NoSerializableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Writeable 的本地化字符串。
        /// </summary>
        internal static string NoWriteable {
            get {
                return ResourceManager.GetString("NoWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyInfo 的本地化字符串。
        /// </summary>
        internal static string PropertyInfo {
            get {
                return ResourceManager.GetString("PropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Readeable 的本地化字符串。
        /// </summary>
        internal static string Readeable {
            get {
                return ResourceManager.GetString("Readeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Rotate {
            get {
                object obj = ResourceManager.GetObject("Rotate", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 SerializableData 的本地化字符串。
        /// </summary>
        internal static string SerializableData {
            get {
                return ResourceManager.GetString("SerializableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SerializableData collection count 的本地化字符串。
        /// </summary>
        internal static string SerializableDataCollectionCount {
            get {
                return ResourceManager.GetString("SerializableDataCollectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShapeAppearance 的本地化字符串。
        /// </summary>
        internal static string ShapeAppearance {
            get {
                return ResourceManager.GetString("ShapeAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagName 的本地化字符串。
        /// </summary>
        internal static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writeable 的本地化字符串。
        /// </summary>
        internal static string Writeable {
            get {
                return ResourceManager.GetString("Writeable", resourceCulture);
            }
        }
    }
}
